### PR TITLE
fix: `waitUntil` and `transaction` type

### PR DESCRIPTION
**Pull request by susiwen8**
- close https://github.com/microsoft/TypeScript/issues/48601
- close https://github.com/microsoft/TypeScript/issues/48553

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
Thanks for helping.
You manipulated a generated file. 
The [correct place](https://github.com/Microsoft/TSJS-lib-generator#input-files) would be `overridingTypes.jsonc`

**Comment by susiwen8** [comment]
> Thanks for helping. You manipulated a generated file. The [correct place](https://github.com/Microsoft/TSJS-lib-generator#input-files) would be `overridingTypes.jsonc`

Thanks!

**Comment by saschanaz** [comment]
There is a reason that `ExtendableEvent.waitUntil` accepts `any`: It basically accept any object and wraps it with `Promise.resolve()` if it's not a promise.

But strictly requiring a promise seems to make a sense in this case.

**Comment by susiwen8** [comment]
> There is a reason that `ExtendableEvent.waitUntil` accepts `any`: It basically accept any object and wraps it with `Promise.resolve()` if it's not a promise.
> 
> But strictly requiring a promise seems to make a sense in this case.

Yes, I saw you [commit](https://github.com/microsoft/TypeScript-DOM-lib-generator/commit/620ea42f857f32716e0e3b0a7a78e69b6c58b043) 3 years ago. 
I read [doc](https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent/waitUntil#parameters) in `MDN`. Telling that `waitUntil` accept a `promise`.

**Comment by susiwen8** [comment]
So I should change `waitUntil` back?

**Comment by saschanaz** [comment]
You can keep it, but you need to follow what @HolgerJeromin said: https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1326#issuecomment-1117415511

**Comment by susiwen8** [comment]
@saschanaz Tests passed. Please take a look.

**Comment by saschanaz** [comment]
It's still running 😉

**Comment by saschanaz** [comment]
lgtm

(Checking if this repo supports automerge)

**Pull request merged**
