### PR TITLE
Add HTMLElement#attachInternals()

### PR DESCRIPTION
**Pull request by naokikimura**
Fixes https://github.com/microsoft/TypeScript/issues/33218

https://github.com/microsoft/TypeScript/pull/36347 was rejected, so I made this PR.

Rather, please tell me why you removed it.

### CODE REVIEW

**Comment by naokikimura** [comment]
@sandersn I would appreciate it if you could review this

**Comment by saschanaz** [comment]
>Rather, please tell me why you removed it.

Those types have only one implementation which is from Chromium, that's why it's removed from here.

**Comment by naokikimura** [comment]
@saschanaz 

Thank you for commenting.

It is already implemented in Firefox Nightly. https://hg.mozilla.org/mozilla-central/rev/e6b60876e668

Does the implementation of that method need to be completed in stable version?

**Comment by saschanaz** [comment]
>Does the implementation of that method need to be completed in stable version?

Yes, as Nightly can always drop it without shipping it to stable.

**Comment by adriengibrat** [comment]
What about moving definition in a separated file so it's up to the user to use it or not (like some ES features) ?

**Comment by saschanaz** [comment]
Currently Definitely Typed is recommended for that purpose.

**Comment by orta** [comment]
I tested support for Firefox and Safari via this glitch app and they're still not available un-flagged: https://web.dev/more-capable-form-controls/#a-working-example

We're still happy to wait until that changes, otherwise as @saschanaz says DT is your best option to get it shipped today

**Comment by saschanaz** [comment]
#1141 and #1149 partially restored ElementInternals types thanks to the new Firefox implementation. Others will be restored when further implementation happens.

@github-actions close

**Pull request closed without merging**
