### PR TITLE
Fix update core dependencies

### PR DESCRIPTION
**Pull request by MattiasBuelens**
The "update core dependencies" workflow is broken again, [see log](https://github.com/microsoft/TypeScript-DOM-lib-generator/actions/runs/8866182335/job/24343313801#step:6:1):
```
Run npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: typescript-dom-lib-generator@0.0.1
npm ERR! Found: eslint@9.1.1
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^9.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^8.56.0" from @typescript-eslint/parser@7.7.1
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"^7.7.1" from the root project
npm ERR!   peer @typescript-eslint/parser@"^7.0.0" from @typescript-eslint/eslint-plugin@7.7.1
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     dev @typescript-eslint/eslint-plugin@"^7.7.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
The problem is that [ESLint version 9 has been released](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/), but [TypeScript ESLint doesn't support it yet](https://github.com/typescript-eslint/typescript-eslint/issues/8211). I worked around it by making `ncu -u` ignore `eslint` for now.

That said, perhaps it would be better if this workflow *only* updated the actual "core dependencies"? [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) accepts a filter argument, so we could do something like this instead:
```
ncu -u '/^@mdn/' '/^@webref/'
```

### CODE REVIEW

**Comment by saschanaz** [comment]
This has never been problem for this long, it has been okay for many years. I guess ESLint 9 contains a lot of huge breaking changes? And yes I think it would be better to have a separate job rather than having a temporary workaround.

**Comment by saschanaz** [comment]
We can also try [8.0.0-alpha.3](https://www.npmjs.com/package/typescript-eslint/v/8.0.0-alpha.3) 🤔

**Comment by MattiasBuelens** [comment]
[ESLint 9](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/) changed the default configuration format to the new "flat config". So we'd need to migrate to the new format, or throw `ESLINT_USE_FLAT_CONFIG=false` into the mix. But either way, it won't be an "automatic" upgrade, we need to make some changes.

Indeed, it looks like we'll need an alpha release of `typescript-eslint` for now, but I can give it a shot if you want?

**Comment by MattiasBuelens** [comment]
Never mind, that alpha version still only supports ESLint v8. Support for ESLint v9 is still being worked on in https://github.com/typescript-eslint/typescript-eslint/pull/9002, so we *cannot* update to v9 at the moment.

I'll see if I can migrate us to the flat config format already. That should hopefully make it easier to update to v9 once TypeScript ESLint adds support.

**Comment by MattiasBuelens** [comment]
That should do it.

The next workflow run should properly update the dependencies again:
```
$ ncu -u -x eslint -x @eslint/js
Upgrading TypeScript-DOM-lib-generator/package.json
[====================] 24/24 100%

 @mdn/browser-compat-data  ^5.5.21  →  ^5.5.23
 @webref/css               ^6.12.7  →  ^6.12.9
 @webref/idl               ^3.46.1  →  ^3.47.1

Run npm install to install new versions.
```

**Comment by saschanaz** [comment]
But again, should we try only updating "core dependencies" rather than doing a temporary workaround? I just opened #1709 which will let Dependabot to do things better, after that this job won't need to update other deps. (It did mostly because Dependabot had no group update, but now it has.)

**Comment by saschanaz** [comment]
https://github.com/typescript-eslint/typescript-eslint/pull/9002 is still open, that should happen too.

**Comment by MattiasBuelens** [comment]
Yeah, I think I'll wait for TypeScript ESLint to get updated first.

**Comment by saschanaz** [comment]
Looks like the dependency tree is now good per #1768, I think we can rebase this and we should be good to go.

**Comment by sandersn** [comment]
I updated the eslint config and then to eslint@9 and ts-eslint@8.

**Comment by saschanaz** [comment]
That auto migration unnecessarily added FlatCompat, would be nice to rebase this and remove that.

**Comment by MattiasBuelens** [comment]
Closing this PR in favor for #1784, which focuses on just the ESLint flat config migration.

**Pull request closed without merging**
