### PR TITLE
ci(workflow): add cache to workflows using actions/setup-node

### PR DESCRIPTION
**Pull request by oscard0m**
## Description

Add `cache` to workflows using `actions/setup-node`

## Context

`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

---

🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾

### CODE REVIEW

**Comment by orta** [comment]
Looks reasonable to me, thanks

**Comment by saschanaz** [comment]
But there is no use for cache when using `npm ci` because it always reinstall everything?

**Comment by oscard0m** [comment]
> But there is no use for cache when using `npm ci` because it always reinstall everything?

I think `npm ci` can use cache to avoid doing some requests, right?

**Comment by saschanaz** [comment]
No, the first thing `npm ci` does is removing `node_modules/` directory.

**Comment by saschanaz** [comment]
Oh, it seems the caching mechanism is not what I thought, it's just the native NPM cache! Sorry, never mind then. 🙇‍♀️

**Pull request merged**
