### PR TITLE
Update @mdn/browser-compat-data to fetch updated mdn API data

### PR DESCRIPTION
**Pull request by Ahmed-Hakeem**
this update will solve this issue  #1384

### CODE REVIEW

**Comment by mathe42** [comment]
You have to run `npm i` `npm run build` and `npm run baseline-accept` localy and commit results!

**Comment by saschanaz** [comment]
https://github.com/mdn/browser-compat-data/issues/17127 is the major blocker here. We'll have to workaround it somehow, probably in bcd-idl-mapper.

**Comment by saschanaz** [comment]
Fixed in #1394, thanks!

@github-actions close

**Comment by Ahmed-Hakeem** [comment]
> Fixed in #1394, thanks!
> 
> 
> 
> @github-actions close

It's my pleasure 😊❤️, I think this will solve this issue but it won't solve your concern here mdn/browser-compat-data#17127 you will have to care about it in every build until you make a workaround inside bcd-idl-mapper.

I hoped you made these changes inside this pull request, but anyway the most important thing is that the issue has been solved, thanks ❤️.

**Comment by saschanaz** [comment]
>I think this will solve this issue but it won't solve your concern here https://github.com/mdn/browser-compat-data/issues/17127 you will have to care about it in every build until you make a workaround inside bcd-idl-mapper.

I worked around it in https://github.com/saschanaz/bcd-idl-mapper/blob/7c0d88d755a5836b9d6e4550f850be2f2e9f8a4b/lib/mixin/search.js#L33, which this generator depends on. For now it should be sufficient for us.

**Comment by Ahmed-Hakeem** [comment]
> >I think this will solve this issue but it won't solve your concern here https://github.com/mdn/browser-compat-data/issues/17127 you will have to care about it in every build until you make a workaround inside bcd-idl-mapper.
> 
> 
> 
> I worked around it in https://github.com/saschanaz/bcd-idl-mapper/blob/7c0d88d755a5836b9d6e4550f850be2f2e9f8a4b/lib/mixin/search.js#L33. For now it should be sufficient for us.

Great, thank you ❤️

**Pull request closed without merging**
