### PR TITLE
Fix PermissionName for clipboard

### PR DESCRIPTION
**Pull request by zhouhanseng**
close https://github.com/DimensionDev/Maskbook/issues/1775

https://www.w3.org/TR/clipboard-apis/#clipboard-permissions

### CODE REVIEW

**Comment by saschanaz** [comment]
LGTM as is, but if you could run `npm run fetch-idl Permissions` and commit it then it would be greater. Thanks!

**Comment by zhouhanseng** [comment]
@saschanaz done thx!

**Comment by Tedko** [comment]
hi @saschanaz any updt?

**Comment by saschanaz** [comment]
Waiting a review from TS team...

**Comment by orta** [comment]
👍🏻

**Pull request merged**
