### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by saschanaz**

### CODE REVIEW

**Comment by orta** [comment]
I think we _just_ missed #1047 being merged at the same time which added you to the package lock, try rebase

**Comment by orta** [comment]
The bot is set to only comment when a PR opens (again, it's very simple) the auth should be working right though, so try the LGTM when its green

**Comment by saschanaz** [comment]
I guess we need a way to escape L1GTM 😄

**Comment by orta** [comment]
7GTM

**Comment by saschanaz** [comment]
LGTM

**Comment by orta** [comment]
ace

**Pull request merged**
