### PR TITLE
Use printUnifiedDiff for faster diffing

### LINKED ISSUE #1580: The NPM deploy job fails on print-diff
Since 369d9d3376f3d4efbd2920eaf64cd659ef7a60db the deploy job hangs too long and times out, and thus the deploy hasn't happened for months.

### PR DESCRIPTION
**Pull request by saschanaz**
This is really for debugging purpose than anything else, so whatever performs faster fits here.

Fixes #1580.

### CODE REVIEW

**Comment by saschanaz** [comment]
Somehow the maintainers assignation is not happening?

LGTM?

**Comment by saschanaz** [comment]
Manually pinging @sandersn since the automation doesn't work 🤔

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
I'm about to quit work for the night, so I'll let this run on its normal schedule to see if this PR fixes the timeout.

**Comment by saschanaz** [comment]
And it worked, thanks!

**Pull request merged**
