### PR TITLE
Exclude features with `version_added: preview`

### PR DESCRIPTION
**Pull request by saschanaz**
See https://github.com/mdn/browser-compat-data/issues/12344 for the reasoning.

### CODE REVIEW

**Comment by orta** [comment]
Picking an arbitrary example, seems reasonable to me:

Screen Shot 2021-09-13 at 2 07 10 PM

**Review by orta — APPROVED** [review]

**Comment by saschanaz** [comment]
LGTM

**Comment by saschanaz** [comment]
They are added just two days ago, so shouldn't be too breaking: https://github.com/microsoft/TypeScript-DOM-lib-generator/releases/tag/%40types%2Fweb%400.0.31

**Comment by orta** [comment]
great, that's not breaking IMO

**Pull request merged**
