### PR TITLE
feat: add resize-observer typs

### PR DESCRIPTION
**Pull request by manucorporat**
However, i got an error when generating the types for Resize Observer:
```
  bareMessage: 'Attributes cannot accept sequence types',
  context: 'Syntax error at line 23, since `interface ResizeObserverEntry`:\n' +
    ' attribute sequence<ResizeObserverSize> borderBoxSize;\n' +
```

fixes https://github.com/microsoft/TypeScript/issues/37861

### CODE REVIEW

**Comment by willstott101** [comment]
Can you try again? Looks like those attributes should be `FrozenArray` not `sequence` as of https://github.com/w3c/csswg-drafts/commit/f1c5335fac18aab1a6394490432e8707a6894645

**Comment by abdonrd** [comment]
Any news here? Thanks in advance!

**Comment by mdingena** [comment]
@manucorporat Seems the build still fails at the `sequence` on line 23 and onwards.

https://github.com/microsoft/TSJS-lib-generator/blob/3ed06f51876b4f843c716eaf21bbf87d600e54f8/inputfiles/idl/Resize%20Observer.widl#L23-L25

https://github.com/microsoft/TSJS-lib-generator/blob/3ed06f51876b4f843c716eaf21bbf87d600e54f8/inputfiles/idl/Resize%20Observer.widl#L38

Should these be `FrozenArray` as well?

PS: Glad to see you're back on it. Hope these difficult times aren't treating you too harshly. I'm very much looking forward to seeing this progressing. Take care!

**Comment by ddprrt** [comment]
There is already an update at https://drafts.csswg.org/resize-observer/ that changes `sequence` to `FrozenArray` everywhere. Don't know when this appears at the public Working Draft's page

**Comment by MatthiasKunnen** [comment]
Also closes #908.

**Comment by TiagoPortfolio** [comment]
Hi all! :wave: 

Thank you so much in advance for adding types for ResizeObserver!
Can I ask why is this taking so long to be reviewed? The last commit was in July.

Cheers!

**Comment by anandtiwary** [comment]
Any update please?

**Comment by timocov** [comment]
I have finished this PR some time ago since it's inactive from its author, see #948.

**Pull request merged**
