### PR TITLE
Add playoutDelayHint to RTCRtpReceiver.

### LINKED ISSUE #953: Add playoutDelayHint to RTPRtcReceiver.
**Search Terms**
playoutDelayHint, playoutDelay

**Suggestion**
Add playoutDelayHint to RTPRtcReceiver.

The API playoutDelayHint as a member to RTCRtpReceiver was introduced in https://henbos.github.io/webrtc-timing/#dom-rtcrtpreceiver-playoutdelayhint and implemented by Chrome. It was adopted by WebRTC extension as defined in https://w3c.github.io/webrtc-extensions/#dom-rtcrtpreceiver-playoutdelay with a different name, even though Chrome has not updated the implementation, and no other major browsers have implemented it.

It would be good to add playoutDelayHint to RTCRtpReceiver for now to enable Chrome. A TODO for the future is to deprecate it and rename it to playoutDelay.

**Use Cases**
In WebRTC based calling, one can use this to adjust the jitter buffer to flavor streaming or conferencing applications.

**Examples**
fippo/webrtc@6f77f10

### PR DESCRIPTION
**Pull request by minyuel**
Fix #953

### CODE REVIEW

**Comment by saschanaz** [comment]
Files in `inputfiles/idl` are not for manual modifications. You might want to add `https://w3c.github.io/webrtc-extensions/` to idlSources.json and run `npm run fetch -- "WebRTC Extensions" && npm run build && npm run baseline-accept`.

**Comment by minyuel** [comment]
Hi Kagami,

Thanks for the review! WebRTC Extensions contains a lot more than playoutDelay, but that might be just good.

But I need to ask you for advice for a special situation. WebRTC Extensions contains playoutDelay but not playoutDelayHint, which is an old version of playoutDelay, and is already in Chrome.

**Comment by saschanaz** [comment]
Oh, is Chrome the only implementation of playoutDelayHint? In that case it shouldn't be included here just yet, [as features need to be implemented on several engines](https://github.com/microsoft/TypeScript-DOM-lib-generator#additions) to make sure they are stable enough.

**Comment by minyuel** [comment]
Hi,

Thanks for the reply!

This might have been well thought of, but to me, if a feature has to be implemented on multiple browsers to be added to TS DOM lib, it sounds a big blocker to the adoption of TS, as many features may be implemented at different paces on different browsers (interop is certainly considered a prerequisite). And on Chrome, some can first undergo an experiment before being settled.

How does TS handle these cases?

**Comment by saschanaz** [comment]
So far the best way to support experimental features is through DefinitelyTyped, so that devs can explicitly know it's not available everywhere.

**Comment by minyuel** [comment]
Ok, thanks! I think that may be what I am really after. Could you point me to how to do PR there?

**Comment by saschanaz** [comment]
Sure. There are several w3c-prefixed packages e.g. [`w3c-generic-sensor`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/w3c-generic-sensor), so you can maybe add `w3c-webrtc-extensions` by `npx dts-gen --dt --name w3c-webrtc-extensions --template global` [per the documentation](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package).

**Comment by minyuel** [comment]
Thanks a lot! For now we can close this PR.

**Pull request closed without merging**
