### PR TITLE
Adds autoGainControl and noiseSuppression properties

### PR DESCRIPTION
**Pull request by paulgalow**
Referring to issue #1148. First PR in this repo. Let me know what I have missed. :)

### CODE REVIEW

**Comment by saschanaz** [comment]
Refer to https://github.com/microsoft/TypeScript-DOM-lib-generator#when-the-type-is-missing:

>If all the conditions are fulfilled, it could be that the type is incorrectly removed by inputfiles/removedTypes.jsonc. Try finding and removing the relevant item there and run npm run build && npm run baseline-accept.

That exactly applies here 😉

**Comment by paulgalow** [comment]
D'oh! I should have been more suspicious. After all this project has the name "generator" in it 🙃. Hope everything's fine now.

**Comment by saschanaz** [comment]
Double checked that those are in Gecko and Blink, since this is touching dictionaries:

* https://searchfox.org/mozilla-central/rev/5966e98bdfa7355e0a3d9cce482f4717dc3419b0/dom/webidl/MediaTrackSettings.webidl#16-17
* https://searchfox.org/mozilla-central/rev/5966e98bdfa7355e0a3d9cce482f4717dc3419b0/dom/webidl/MediaTrackSettings.webidl#16-17
* https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/mediastream/media_track_settings.idl;l=17-18;drc=6b2f5b4d453a7dcd7c13399965d02b3224c7277d
* https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/mediastream/media_track_constraint_set.idl;l=23-24;drc=38f8aed3833a0063dc63fdaba766d584cdb48264

So, LGTM.

**Comment by paulgalow** [comment]
Thanks for pointing me in the right direction and also for your blazingly fast response.

**Pull request merged**
