### PR TITLE
added databases function to IDBFactory interface

### PR DESCRIPTION
**Pull request by fritzschoff**
fixes microsoft/TypeScript#37317
and fixes microsoft/TypeScript#36706

### CODE REVIEW

**Comment by orta** [comment]
👋  hi there, it looks like you edited the generated file by hand - these changes would get overwritten when someone else makes a change. You could try updating [the WIDL](https://github.com/microsoft/TSJS-lib-generator#contribution-guidelines) for these specs to add the new properties!

**Comment by fritzschoff** [comment]
Hey @orta I updated the widl file know, I hope this is what you mean with your comment above. To be honest, I never worked with a widl file, if anything is missing, please let me know!

**Comment by orta** [comment]
Cool, did you run the script to update it from the website? e.g. `npm run fetch-idl "Indexed Databases" && npm run build && npm run baseline-accept`

**Comment by fritzschoff** [comment]
Hey @orta , just ran the command and the generated files got updated, but I couldn't tell the configuration that the return value is `Promise<IDBDatabases[]>`, I was only capable of doing `Promise<IDBDatabases>` without the [ ] brackets. Is there a specific syntax for this configuration to generating an array? Also the placement now of this generated method is a bit displaced, can I move it by hand?

**Review by lastthyme — APPROVED** [review]

**Pull request closed without merging**
