### PR TITLE
Add back RequestInit.priority property

### PR DESCRIPTION
**Pull request by SevenOutman**
Fix microsoft/TypeScript#54472

As of today (2023-06), `RequestInit.priority` ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters)) already has considerable range of support [according to caniuse.com](https://caniuse.com/mdn-api_fetch_init_priority_parameter)

image

### Additional Info

The generated `RequestInit.priority` doesn't have a descriptive comment. I found that comments for other `RequestInit` members are located in `inputfiles/idl/fetch.commentmap.json`, the [README](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/2d110ad3bd0e4f91bcfe2ab99fcd5cef02c36e11/inputfiles/idl/README.md) informs that this file should be updated with `npm run fetch` but this script seems missing now. How could I add the comments?

### CODE REVIEW

**Comment by SevenOutman** [comment]
@microsoft-github-policy-service agree

**Comment by HolgerJeromin** [comment]
> As of today (2023-06), RequestInit.priority (MDN) already has considerable range of support according to caniuse.com

No. This is all one engine (blink).

https://github.com/microsoft/TypeScript-DOM-lib-generator#when-the-type-is-missing

**Review by max-carroll-sky — APPROVED** [review]
LGTM

**Comment by davecardwell** [comment]
Could this be reconsidered for merging please?

- It is standardized in the `fetch` spec: https://fetch.spec.whatwg.org/#request-priority
- Safari have implemented it in the Technology Preview version ([initially behind flag](https://github.com/WebKit/WebKit/commit/69a182bca140bcc4d604dd6eba4ea48a16e9d00a), [enabled by default](https://github.com/WebKit/WebKit/commit/793f132ba08ba69462713ded8e74294bd400023e))
- Firefox have it [ticketed](https://bugzilla.mozilla.org/show_bug.cgi?id=1839319) as part of their [Fetch Priority work](https://bugzilla.mozilla.org/show_bug.cgi?id=1797715)

cc/ @saschanaz @HolgerJeromin

**Comment by HolgerJeromin** [comment]
#1654 added fetchprio for image because of
https://github.com/mdn/browser-compat-data/pull/21267
Perhaps we should merge this very pr now.

**Comment by saschanaz** [comment]
(But this PR has conflict)

**Comment by SevenOutman** [comment]
> (But this PR has conflict)

I'll have them resolved this week.

**Comment by SevenOutman** [comment]
@saschanaz Conflicts resovled.

**Comment by saschanaz** [comment]
Lgtm

**Pull request merged**
