### PR TITLE
Replace Promises with union types in callbacks

### PR DESCRIPTION
**Pull request by saschanaz**
A cleanup before updating Streams types.

### CODE REVIEW

**Review by sandersn — CHANGES_REQUESTED** [review]
I'm worried about this breaking callbacks that only return PromiseLike instead of Promise. Can you explain why this was PromiseLike originally? Was that incorrect? Will these be good breaks?

**Comment by saschanaz** [comment]
No, it turns out that PromiseLike must be used as general thenables should also work.

**Comment by saschanaz** [comment]
Some problems, will reopen soon

**Comment by saschanaz** [comment]
Never mind, my confusion 👀

**Comment by sandersn** [comment]
The diff looks OK now, just need to get the build passing

**Comment by saschanaz** [comment]
@sandersn That's #903, it needs some love.

**Comment by saschanaz** [comment]
Replaced by #1034

**Pull request closed without merging**
