### PR TITLE
2nd Minor PR

### PR DESCRIPTION
**Pull request by orta**
@saschanaz should be able to merge this

### CODE REVIEW

**Review by saschanaz — APPROVED** [review]

**Comment by orta** [comment]
It only accepts "LGTM"  in a comment from you, (that comment can live in a review though!)

**Comment by saschanaz** [comment]
>It only accepts "LGTM" in a comment from you

That's very... weird? 🤔

**Comment by saschanaz** [comment]
LGTM

**Comment by orta** [comment]
alright bot, chill out

**Pull request merged**
