### PR TITLE
Don't run the TS tests unless baselines change

### PR DESCRIPTION
**Pull request by orta**
Should reduce CI times for a some PRs

### CODE REVIEW

**Comment by saschanaz** [comment]
I wonder doing this will skip the tests when someone only updates `inputfiles/` and forgets to update baselines.

**Comment by saschanaz** [comment]
Probably should also cover `inputfiles` and `package-lock.json` since updating webref and bcd also affects baselines.

**Comment by saschanaz** [comment]
Or maybe better to filter out irrelevant paths by `paths-ignore`.

**Comment by orta** [comment]
Any changes to the other files without a corresponding baseline change would mean that the normal `npm test` CI would fail, making the build red anyway. At that point there's no need to run the run these more intense tests.

**Comment by saschanaz** [comment]
Ah yeah, I misunderstood 👀 Okay then.

**Pull request merged**
