### PR TITLE
Add support for `WEBGL_compressed_texture_pvrtc`

### PR DESCRIPTION
**Pull request by SuperSodaSea**
In mdn/browser-compat-data#18692 and mdn/browser-compat-data#18704 the BCD for `WEBGL_compressed_texture_pvrtc` is updated. With the latest BCD there are two major browser engines (Blink & WebKit) that support `WEBGL_compressed_texture_pvrtc`, so we can add interface `WEBGL_compressed_texture_pvrtc` and `getExtension(extensionName: "WEBGL_compressed_texture_pvrtc")` now.

### CODE REVIEW

**Comment by SuperSodaSea** [comment]
@microsoft-github-policy-service agree

**Comment by SuperSodaSea** [comment]
Seems that some problems need to be solve in #1481 and mdn/browser-compat-data#18710. I will wait for them to be solved.

**Comment by saschanaz** [comment]
BCD is updated, please merge.

**Comment by SuperSodaSea** [comment]
Done!

**Comment by saschanaz** [comment]
Please don't update package.json here as doing so requires another review which happens not so frequently.

**Comment by SuperSodaSea** [comment]
Okay, changes in package.json are reverted.

**Comment by saschanaz** [comment]
Thanks! LGTM

**Pull request merged**
